name: simple-pagination

on:
  pull_request:
    branches: [main]


jobs:
  continuous-integration:
    runs-on: ubuntu-latest # 환경 
    steps: # line by line으로 수행
    - uses: action/checkout@v3
    - uses: action/setup-node@v3 # node 환경에서 돌리기 위해
      with:
        node-version: 18.x

    - name: Run Continuous Integration
      run: |
        npm ci 
        npm test